import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import { env } from './config/env.js';
import { connectDatabase } from './config/database.js';
import { checkOrigin } from './middlewares/auth.js';
import { errorHandler, HttpError, send } from './utils/errors.js';
import router from './routes/index.js';
const app = express();
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({ credentials: true, origin(origin, callback) { callback(null, !origin || env.origins.includes(origin)); } }));
app.use(express.json({ limit: '32kb' }));
app.use(cookieParser());
app.get(['/api/health', '/api/v1/health'], (req, res) => send(res, { service: 'KelseTS Cars API', version: 'v1', status: 'ok' }));
app.use('/api/v1', checkOrigin, async (req, res, next) => { await connectDatabase(); next(); }, router);
app.use((req, res, next) => next(new HttpError(404, 'Ruta no encontrada.')));
app.use(errorHandler);
export default app;
