import { Router } from 'express';
import { rateLimit } from 'express-rate-limit';
import multer from 'multer';
import { VEHICLE_IMAGE_MAX_BYTES } from '@kelsets-cars/contracts';
import { authenticate, allowRoles } from '../middlewares/auth.js';
import * as auth from '../modules/auth/controllers/auth.js';
import * as catalog from '../modules/catalog/controllers/catalog.js';
import * as appointments from '../modules/appointments/controllers/appointments.js';
import { uploadVehicleImage } from '../modules/catalog/controllers/images.js';
import * as workshops from '../modules/workshops/controllers.js';
import { listMessages } from '../modules/communications/controllers.js';
const router = Router();
const accessLimit = rateLimit({ windowMs: 15 * 60000, limit: 20, standardHeaders: 'draft-8', legacyHeaders: false, message: { success: false, error: 'Demasiados intentos. Espera unos minutos.' } });
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: VEHICLE_IMAGE_MAX_BYTES, files: 1 }, fileFilter(req, file, cb) { cb(null, ['image/jpeg', 'image/png', 'image/webp'].includes(file.mimetype)); } });
router.post('/auth/register', accessLimit, auth.register);
router.post('/auth/login', accessLimit, auth.login);
router.post('/auth/logout', auth.logout);
router.get('/auth/me', authenticate, auth.me);
router.get('/messages', authenticate, listMessages);
router.get('/workshops', workshops.listPublicWorkshops);
router.get('/workshops/assignable', authenticate, allowRoles('admin'), workshops.assignableWorkshops);
router.get('/workshops/me', authenticate, workshops.myWorkshop);
router.get('/workshops/jobs', authenticate, allowRoles('workshop'), workshops.myJobs);
router.get('/workshops/applications', authenticate, allowRoles('admin'), workshops.listApplications);
router.patch('/workshops/:id/review', authenticate, allowRoles('admin'), workshops.reviewApplication);
router.get('/vehicles', catalog.listVehicles);
router.get('/vehicles/search-options', catalog.searchOptions);
router.get('/vehicles/:id', catalog.getVehicle);
router.post('/vehicles/:id/image', authenticate, allowRoles('admin'), upload.single('image'), uploadVehicleImage);
router.get('/dealerships', catalog.listDealerships);
const appointmentAccess = (req, res, next) => {
  if (req.user.accountType === 'workshop' || req.user.role === 'workshop') return res.status(403).json({ success: false, error: 'Esta cuenta profesional no tiene acceso a la agenda de clientes.' });
  next();
};
router.get('/appointments', authenticate, appointmentAccess, appointments.listAppointments);
router.post('/appointments', authenticate, appointmentAccess, appointments.createAppointment);
router.patch('/appointments/:id', authenticate, appointmentAccess, appointments.updateAppointment);
router.post('/appointments/:id/workshop', authenticate, allowRoles('admin'), appointments.assignWorkshop);
export default router;
