import { Router } from 'express';
import { rateLimit } from 'express-rate-limit';
import multer from 'multer';
import { authenticate, allowRoles } from '../middlewares/auth.js';
import * as auth from '../modules/auth/controllers/auth.js';
import * as catalog from '../modules/catalog/controllers/catalog.js';
import * as appointments from '../modules/appointments/controllers/appointments.js';
import { uploadVehicleImage } from '../modules/catalog/controllers/images.js';
const router = Router();
const accessLimit = rateLimit({ windowMs: 15 * 60000, limit: 20, standardHeaders: 'draft-8', legacyHeaders: false, message: { success: false, error: 'Demasiados intentos. Espera unos minutos.' } });
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024, files: 1 }, fileFilter(req, file, cb) { cb(null, ['image/jpeg', 'image/png', 'image/webp'].includes(file.mimetype)); } });
router.post('/auth/register', accessLimit, auth.register);
router.post('/auth/login', accessLimit, auth.login);
router.post('/auth/logout', auth.logout);
router.get('/auth/me', authenticate, auth.me);
router.get('/vehicles', catalog.listVehicles);
router.get('/vehicles/:id', catalog.getVehicle);
router.post('/vehicles/:id/image', authenticate, allowRoles('admin'), upload.single('image'), uploadVehicleImage);
router.get('/dealerships', catalog.listDealerships);
router.get('/appointments', authenticate, appointments.listAppointments);
router.post('/appointments', authenticate, appointments.createAppointment);
router.patch('/appointments/:id', authenticate, appointments.updateAppointment);
export default router;
