import { useCallback } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api } from '../../shared/services/api.js';
import { useResource } from '../../shared/hooks/useResource.js';
import { ResourceState } from '../../shared/components/ResourceState.jsx';
import { VehiclePhoto } from '../../shared/components/VehiclePhoto.jsx';
export function CatalogPage() {
  const [params, setParams] = useSearchParams();
  const query = params.toString();
  const load = useCallback(signal => api.catalog.list(query, { signal }), [query]);
  const resource = useResource(load);
  function filter(event) { event.preventDefault(); const values = new URLSearchParams(new FormData(event.currentTarget)); values.set('page', '1'); setParams(values); }
  function page(number) { const next = new URLSearchParams(params); next.set('page', String(number)); setParams(next); }
  return <section className="page-shell"><p className="eyebrow">LA COLECCIÓN</p><h1>Encuentra tu<br /><em>próximo camino.</em></h1><p>Consulta el inventario y descubre cada vehículo con su sede de referencia.</p><form className="filters" onSubmit={filter} key={query}><label>Buscar<input name="q" defaultValue={params.get('q') || ''} placeholder="Marca o modelo" maxLength={100} /></label><label>Marca<select name="brand" defaultValue={params.get('brand') || ''}><option value="">Todas las marcas</option>{(resource.data?.brands || ['Tesla', 'Mercedes-Benz', 'Audi', 'Ferrari', 'Porsche']).map(value => <option key={value}>{value}</option>)}</select></label><label>Motorización<select name="fuel" defaultValue={params.get('fuel') || ''}><option value="">Todas</option>{(resource.data?.fuels || ['Eléctrico', 'Por verificar']).map(value => <option key={value}>{value}</option>)}</select></label><label>Ordenar<select name="sort" defaultValue={params.get('sort') || 'brand'}><option value="brand">Marca y modelo</option><option value="price-asc">Precio: menor a mayor</option><option value="price-desc">Precio: mayor a menor</option></select></label><button className="button">Aplicar filtros</button></form><ResourceState resource={resource}>{data => <><p role="status">{data.total} vehículos</p>{data.items.length ? <div className="editorial-grid">{data.items.map(vehicle => <article className="editorial-card" key={vehicle._id}><VehiclePhoto src={vehicle.image} alt={`${vehicle.brand} ${vehicle.model}, fotografía ilustrativa`} /><div><p className="eyebrow">{vehicle.brand}</p><h2>{vehicle.model}</h2><p>{vehicle.year || 'Año pendiente'} · {vehicle.dealership?.city}</p><p>{vehicle.price == null ? 'Precio pendiente' : new Intl.NumberFormat('es-ES', { style: 'currency', currency: vehicle.currency || 'EUR', maximumFractionDigits: 0 }).format(vehicle.price)}</p><Link to={`/vehiculos/${vehicle._id}`}>Ver ficha ↗</Link></div></article>)}</div> : <div className="notice"><h2>No hay vehículos con estos filtros</h2><button className="button" onClick={() => setParams({})}>Limpiar filtros</button></div>}<div className="pagination"><button className="button button-outline" disabled={data.page <= 1} onClick={() => page(data.page - 1)}>Anterior</button><span>Página {data.page} de {Math.max(data.pages, 1)}</span><button className="button button-outline" disabled={data.page >= data.pages} onClick={() => page(data.page + 1)}>Siguiente</button></div></>}</ResourceState></section>;
}
